DROP DATABASE IF EXISTS `Acme-Showroom`;
CREATE DATABASE `Acme-Showroom`;

USE `Acme-Showroom`;

GRANT SELECT, INSERT, UPDATE, DELETE 
  ON `Acme-Showroom`.* TO 'acme-user'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, 
    CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, CREATE ROUTINE, 
    ALTER ROUTINE, EXECUTE, TRIGGER, SHOW VIEW
  ON `Acme-Showroom`.* TO 'acme-manager'@'%';
